language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
        - EXECUTE_COVERAGE=true
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 7.0
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist

script:
  - mkdir -p build/logs
  - if [ "$EXECUTE_COVERAGE" != "true" ]; then phpunit; fi
  - if [ "$EXECUTE_COVERAGE" == "true" ]; then phpunit --coverage-clover build/logs/clover.xml; fi
  - if [ "$EXECUTE_CS_CHECK" == "true" ]; then vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi

after_script:
  - php vendor/bin/coveralls -v
